spring:
  application:
    name: aftourism-portal
  datasource:
    url: jdbc:mysql://localhost:3306/aftourism_server?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.aftourism.portal.pojo
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8082
